const API="https://evida-france.netlify.app/.netlify/functions";
const PRODUCTS=[
  {id:208,section:"compagnons",category:"ESSENTIEL ANIMAUX",name:"Brosse anti-poils 2-en-1",price:10.09,image:"https://cf.cjdropshipping.com/17170272/2405300600490321700.jpg",description:"Pour retirer les poils sur les vêtements, tissus et sièges.",personalized:false},
  {id:207,section:"compagnons",category:"PETITE ATTENTION",name:"Pendentif cœur chat & petit chien",price:11.99,image:"https://oss-cf.cjdropshipping.com/product/2024/01/25/08/fc656ad1-91e0-4578-b365-34ab33f362b1.jpg",description:"Un pendentif décoratif à offrir à un amoureux des animaux.",personalized:false},
  {id:206,section:"compagnons",category:"SOUVENIR PERSONNALISÉ",name:"Plaid personnalisé — portrait d’animal",price:39.90,image:"assets/products/plaid-animal.webp",description:"Ajoutez sa photo pour créer un plaid qui lui ressemble.",personalized:true},
  {id:209,section:"selections",category:"PRATIQUE AU QUOTIDIEN",name:"Batterie externe compacte — jusqu’à 20 000 mAh",price:38.99,image:"https://oss-cf.cjdropshipping.com/product/2025/02/23/08/ebf4f21e-88f5-49f1-aa76-a81e04d752ad_trans.jpeg",description:"Une batterie compacte à glisser dans un sac ou à garder à portée de main.",personalized:false},
  {id:210,section:"selections",category:"NE PERDEZ PLUS L’ESSENTIEL",name:"Balise Bluetooth anti-perte",price:7.99,image:"https://cf.cjdropshipping.com/15139872/1547729804061.jpg",description:"Pour garder un œil sur les objets importants au quotidien.",personalized:false},
  {id:211,section:"selections",category:"BUREAU & MAISON",name:"Support téléphone/tablette rotatif 360°",price:2.99,image:"https://oss-cf.cjdropshipping.com/product/2024/04/01/05/6de0dea8-d7a8-4c9f-ad03-b37f11e1b761.jpg",description:"Un support de bureau simple pour garder son écran à hauteur.",personalized:false},
  {id:212,section:"maison",category:"À EMPORTER",name:"Blender portable rechargeable",price:8.99,image:"https://cf.cjdropshipping.com/quick/product/bef87977-9a0d-4099-826a-75bdcae7a2f9.jpg",description:"Un mini blender rechargeable pour préparer vos boissons facilement.",personalized:false},
  {id:213,section:"maison",category:"AMBIANCE MAISON",name:"Diffuseur d’arômes effet flamme",price:6.99,image:"https://oss-cf.cjdropshipping.com/product/2024/09/30/06/f8c292ac-be2b-4330-9058-f321cd75720f.jpg",description:"Un diffuseur compact pour créer une ambiance chaleureuse.",personalized:false},
  {id:214,section:"maison",category:"PRATIQUE EN VOYAGE",name:"Défroisseur portable USB",price:4.99,image:"https://oss-cf.cjdropshipping.com/product/2025/08/16/09/4d5163f2-6002-43df-8402-fd92e81e5b72_trans.jpeg",description:"Un format compact pour rafraîchir vos vêtements hors de chez vous.",personalized:false},
  {id:215,section:"maison",category:"BIEN-ÊTRE",name:"Correcteur de posture intelligent",price:57.99,image:"https://cf.cjdropshipping.com/1617170852159.jpg",description:"Un accessoire discret à utiliser au quotidien.",personalized:false}
];

let cart=[],pendingPhoto=null,addressTimer=null;
try{cart=JSON.parse(sessionStorage.getItem("evida-cart")||"[]")}catch{}
const $=x=>document.getElementById(x);
const euro=n=>n.toLocaleString("fr-FR",{style:"currency",currency:"EUR"});

function save(){sessionStorage.setItem("evida-cart",JSON.stringify(cart));renderCart()}
function card(p){return `<article class="product"><div class="visual"><img src="${p.image}" alt="${p.name}"></div><div class="body"><div class="tag">${p.category}</div><h3>${p.name}</h3><div class="desc">${p.description}</div><div class="price">${euro(p.price)}</div><div class="shipping">Livraison suivie : tarif affiché avant paiement</div><button class="add" data-id="${p.id}">${p.personalized?"Personnaliser":"Ajouter au panier"}</button></div></article>`}
function renderProducts(){for(const s of["selections","maison","compagnons"]){$("grid-"+s).innerHTML=PRODUCTS.filter(p=>p.section===s).map(card).join("")}document.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>add(Number(b.dataset.id)))}
function add(id){const p=PRODUCTS.find(x=>x.id===id);if(p.personalized){pendingPhoto=null;$("photoForm").reset();$("preview").style.display="none";$("photoDialog").showModal();return}cart.push({...p,lineId:crypto.randomUUID(),quantity:1});save();openCart()}

$("photo").onchange=async e=>{const f=e.target.files[0];if(!f)return;const b=await createImageBitmap(f),s=Math.min(1,1500/Math.max(b.width,b.height)),c=document.createElement("canvas");c.width=Math.round(b.width*s);c.height=Math.round(b.height*s);c.getContext("2d").drawImage(b,0,0,c.width,c.height);pendingPhoto={data:c.toDataURL("image/jpeg",.82),type:"image/jpeg",name:f.name};b.close();$("preview").src=pendingPhoto.data;$("preview").style.display="block"};
$("photoForm").onsubmit=e=>{e.preventDefault();if(!pendingPhoto)return $("photoStatus").textContent="Ajoutez une photo.";const p=PRODUCTS.find(x=>x.id===206);cart.push({...p,lineId:crypto.randomUUID(),quantity:1,personalization:{text:$("customText").value.trim(),photo:pendingPhoto,photoValidated:true}});save();$("photoDialog").close();openCart()};

function renderCart(){$("cartCount").textContent=cart.length;$("cartItems").innerHTML=cart.length?cart.map(x=>`<div class="cartItem"><strong>${x.name}</strong><div>${euro(x.price)}</div><button data-rm="${x.lineId}">Retirer</button></div>`).join(""):"Votre panier est vide.";document.querySelectorAll("[data-rm]").forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.lineId!==b.dataset.rm);save()});const sub=cart.reduce((a,x)=>a+x.price,0);$("subtotal").textContent=euro(sub);$("shipping").textContent=cart.length?"Calculée à l’adresse":euro(0);$("total").textContent=euro(sub)}
function openCart(){$("drawer").classList.add("open");$("overlay").classList.add("show")}
function closeCart(){$("drawer").classList.remove("open");$("overlay").classList.remove("show")}
$("openCart").onclick=openCart;$("closeCart").onclick=closeCart;$("overlay").onclick=closeCart;
document.querySelectorAll(".x").forEach(x=>x.onclick=()=>x.closest("dialog").close());
$("checkout").onclick=()=>{if(!cart.length)return;const pers=cart.some(x=>x.personalized);$("photoConsentRow").style.display=pers?"flex":"none";$("salesConsentRow").style.display=pers?"flex":"none";$("checkoutForm").elements.photoConsent.required=pers;$("checkoutForm").elements.salesConsent.required=pers;closeCart();$("checkoutDialog").showModal()};

function clearAddr(){$("addressValidatedInput").value="false";$("postalCodeInput").value="";$("cityInput").value="";$("cityCodeInput").value="";$("addressLabelInput").value="";$("addressError").hidden=true}
$("addressInput").addEventListener("input",()=>{clearAddr();const q=$("addressInput").value.trim();clearTimeout(addressTimer);if(q.length<4){$("addressSuggestions").hidden=true;return}addressTimer=setTimeout(()=>loadAddr(q),250)});
async function loadAddr(q){try{const r=await fetch(`${API}/address-search?q=${encodeURIComponent(q)}`),d=await r.json();const box=$("addressSuggestions");box.innerHTML="";for(const a of d.suggestions||[]){const b=document.createElement("button");b.type="button";b.textContent=a.label;b.onclick=()=>{$("addressInput").value=a.street||a.label;$("postalCodeInput").value=a.postcode;$("cityInput").value=a.city;$("cityCodeInput").value=a.citycode||"";$("addressLabelInput").value=a.label;$("addressValidatedInput").value="true";$("addressError").hidden=true;box.hidden=true};box.appendChild(b)}box.hidden=!box.children.length}catch{$("addressSuggestions").hidden=true}}

$("checkoutForm").onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),pers=cart.some(x=>x.personalized),status=$("checkoutStatus");if(fd.get("addressValidated")!=="true"){$("addressError").hidden=false;return}const body={customer:{firstName:fd.get("firstName"),lastName:fd.get("lastName"),email:fd.get("email"),phone:fd.get("phone"),address:fd.get("address"),postalCode:fd.get("postalCode"),city:fd.get("city"),cityCode:fd.get("cityCode"),addressLabel:fd.get("addressLabel")},voucherCode:String(fd.get("voucherCode")||"").trim(),photoConsent:!pers||fd.get("photoConsent")==="on",salesConsent:!pers||fd.get("salesConsent")==="on",items:cart.map(x=>({id:x.id,quantity:1,personalization:x.personalization||null}))};try{$("pay").disabled=true;status.textContent="Validation de l’adresse…";let r=await fetch(API+"/address-validate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body.customer)}),d=await r.json();if(!r.ok||!d.valid)throw new Error(d.error||"Adresse non reconnue.");body.customer={...body.customer,...d.address};status.textContent="Calcul de la livraison…";r=await fetch(API+"/shipping-quote",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer:body.customer,items:body.items})});d=await r.json();if(!r.ok)throw new Error(d.error||"Livraison indisponible.");body.shippingQuote=d.quote;$("shippingQuote").textContent=`Livraison suivie : ${euro(d.quote.amountEur)} — ${d.quote.logisticName}`;status.textContent="Ouverture du paiement SumUp…";r=await fetch(API+"/create-checkout-session-v2",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});d=await r.json();if(!r.ok||!d.url)throw new Error(d.error||"Paiement indisponible.");location.href=d.url}catch(err){status.textContent=err.message;$("pay").disabled=false}};

renderProducts();renderCart();
