const API="https://evida-france.netlify.app/.netlify/functions";
const PRODUCTS=[
{id:208,category:"Animaux",name:"Brosse anti-poils 2-en-1 — vêtements & textiles",price:10.09,image:"https://cf.cjdropshipping.com/17170272/2405300600490321700.jpg",description:"La vraie brosse rouleau 2-en-1 du fournisseur CJ, pour retirer les poils sur vêtements, canapé et textiles.",details:"Photo officielle CJ · ABS · blanc/orange · mouvement aller-retour · SKU CJMY200580801AZ",personalized:false},
{id:207,category:"Animaux",name:"Pendentif cœur pour chat & petit chien — collier perlé",price:11.99,image:"https://oss-cf.cjdropshipping.com/product/2024/01/25/08/fc656ad1-91e0-4578-b365-34ab33f362b1.jpg",description:"Un vrai pendentif décoratif porté par l’animal : collier perlé avec petit cœur.",details:"Même fournisseur CJ · cœur bleu saphir · taille S 20+5 cm · SKU CJGX195184801AZ",personalized:false},
{id:206,category:"Personnalisé",name:"Plaid personnalisé — portrait d’animal",price:39.90,image:"https://raw.githubusercontent.com/Evida-france/evida-fr.github.io/main/assets/products/plaid-animal.webp",description:"Ajoutez la photo de votre animal pour fabriquer votre plaid personnalisé.",details:"Photo liée à la commande · validation avant fabrication",personalized:true}
];
let cart=[],cat="Tous",pendingPhoto=null;try{cart=JSON.parse(sessionStorage.getItem("evida-cart")||"[]")}catch{}
const $=x=>document.getElementById(x),euro=n=>n.toLocaleString("fr-FR",{style:"currency",currency:"EUR"});
function save(){sessionStorage.setItem("evida-cart",JSON.stringify(cart));renderCart()}
function renderProducts(){const q=$("search").value.toLowerCase().trim();const rows=PRODUCTS.filter(p=>(cat==="Tous"||p.category===cat)&&(p.name.toLowerCase().includes(q)||p.description.toLowerCase().includes(q)));$("grid").innerHTML=rows.map(p=>`<article class="product"><div class="visual"><img src="${p.image}" alt="${p.name}"></div><div class="body"><div class="tag">${p.category}</div><h3>${p.name}</h3><div class="desc">${p.description}</div><div class="details">${p.details}</div><div class="price">${euro(p.price)}</div><div class="shipping">Livraison 4,90 € · offerte dès 50 €</div><button class="add" data-id="${p.id}">${p.personalized?"Personnaliser":"Ajouter au panier"}</button></div></article>`).join("");document.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>add(Number(b.dataset.id)))}
function add(id){const p=PRODUCTS.find(x=>x.id===id);if(p.personalized){pendingPhoto=null;$("photoForm").reset();$("preview").style.display="none";$("photoDialog").showModal();return}cart.push({...p,lineId:crypto.randomUUID(),quantity:1});save();openCart()}
$("photo").onchange=async e=>{const f=e.target.files[0];if(!f)return;const b=await createImageBitmap(f),s=Math.min(1,1500/Math.max(b.width,b.height)),c=document.createElement("canvas");c.width=Math.round(b.width*s);c.height=Math.round(b.height*s);c.getContext("2d").drawImage(b,0,0,c.width,c.height);pendingPhoto={data:c.toDataURL("image/jpeg",.82),type:"image/jpeg",name:f.name};b.close();$("preview").src=pendingPhoto.data;$("preview").style.display="block"};
$("photoForm").onsubmit=e=>{e.preventDefault();if(!pendingPhoto)return $("photoStatus").textContent="Ajoutez une photo.";if(!$("photoOk").checked)return;const p=PRODUCTS.find(x=>x.id===206);cart.push({...p,lineId:crypto.randomUUID(),quantity:1,personalization:{text:$("customText").value.trim(),finish:"Impression portrait",size:"Format standard",photo:pendingPhoto,photoValidated:true}});save();$("photoDialog").close();openCart()};
function renderCart(){$("cartCount").textContent=cart.length;$("cartItems").innerHTML=cart.length?cart.map(x=>`<div class="cartItem"><strong>${x.name}</strong><div>${euro(x.price)}</div><button data-rm="${x.lineId}">Retirer</button></div>`).join(""):"Votre panier est vide.";document.querySelectorAll("[data-rm]").forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.lineId!==b.dataset.rm);save()});const sub=cart.reduce((a,x)=>a+x.price,0),ship=cart.length?(sub>=50?0:4.90):0;$("subtotal").textContent=euro(sub);$("shipping").textContent=ship?euro(ship):cart.length?"Offerte":euro(0);$("total").textContent=euro(sub+ship)}
function openCart(){$("drawer").classList.add("open");$("overlay").classList.add("show")}function closeCart(){$("drawer").classList.remove("open");$("overlay").classList.remove("show")}
$("openCart").onclick=openCart;$("closeCart").onclick=closeCart;$("overlay").onclick=closeCart;document.querySelectorAll(".x").forEach(x=>x.onclick=()=>x.closest("dialog").close());
$("checkout").onclick=()=>{if(!cart.length)return $("payStatus").textContent="Votre panier est vide.";const pers=cart.some(x=>x.personalized);$("photoConsentRow").style.display=pers?"flex":"none";$("salesConsentRow").style.display=pers?"flex":"none";$("checkoutForm").elements.photoConsent.required=pers;$("checkoutForm").elements.salesConsent.required=pers;closeCart();$("checkoutDialog").showModal()};
$("checkoutForm").onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),pers=cart.some(x=>x.personalized),status=$("checkoutStatus");status.textContent="Ouverture du paiement SumUp…";const body={customer:{firstName:fd.get("firstName"),lastName:fd.get("lastName"),email:fd.get("email"),address:fd.get("address"),postalCode:fd.get("postalCode"),city:fd.get("city")},photoConsent:!pers||fd.get("photoConsent")==="on",salesConsent:!pers||fd.get("salesConsent")==="on",items:cart.map(x=>({id:x.id,quantity:1,personalization:x.personalization||null}))};try{const r=await fetch(API+"/create-checkout-session-v2",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok||!d.url)throw new Error(d.error||"Paiement indisponible.");location.href=d.url}catch(err){status.textContent=err.message}};
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{cat=b.dataset.cat;document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderProducts()});$("search").oninput=renderProducts;renderProducts();renderCart();