import {PRODUCTS} from "./products.mjs";
const BASE="https://developers.cjdropshipping.com/api2.0/v1";
let cache={token:"",expires:0};
async function cjToken(){const apiKey=process.env.CJ_API_KEY;if(!apiKey)throw new Error("CJ_API_KEY manquante dans Netlify.");if(cache.token&&Date.now()<cache.expires)return cache.token;const r=await fetch(`${BASE}/authentication/getAccessToken`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({apiKey})});const d=await r.json();if(!r.ok||!d?.data?.accessToken)throw new Error(d?.message||"Authentification CJ impossible.");cache={token:d.data.accessToken,expires:Date.now()+23*60*60*1000};return cache.token}
async function cjFetch(path,options={}){const token=await cjToken();const r=await fetch(BASE+path,{...options,headers:{"CJ-Access-Token":token,"Content-Type":"application/json",...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok||d?.result===false||d?.success===false)throw new Error(d?.message||`Erreur CJ ${r.status}`);return d}
async function resolveVid(sku){const d=await cjFetch(`/product/variant/query?variantSku=${encodeURIComponent(sku)}`);const rows=Array.isArray(d.data)?d.data:[d.data].filter(Boolean);const x=rows.find(v=>String(v.variantSku||v.sku||"").toUpperCase()===String(sku).toUpperCase())||rows[0];const vid=x?.vid||x?.id||x?.variantId;if(!vid)throw new Error(`Variante CJ introuvable pour ${sku}.`);return {vid,sku}}
async function usdToEur(){const fallback=Number(process.env.CJ_USD_EUR_RATE||0.86);try{const r=await fetch("https://api.frankfurter.app/latest?from=USD&to=EUR");const d=await r.json();const v=Number(d?.rates?.EUR);return v>0?v:fallback}catch{return fallback}}
export async function quoteShipping(customer,items){const cjItems=[];for(const item of items){const p=PRODUCTS[Number(item.id)];if(!p)throw new Error("Produit invalide.");if(!p.cj)continue;const v=await resolveVid(p.sku);cjItems.push({quantity:Number(item.quantity||1),vid:v.vid,sku:p.sku})}if(!cjItems.length)return {amountUsd:0,amountEur:0,logisticName:"Hors CJ",aging:"",cjItems:[],quotedAt:new Date().toISOString()};const payload={startCountryCode:"CN",endCountryCode:"FR",zip:customer.postalCode,products:cjItems.map(x=>({quantity:x.quantity,vid:x.vid}))};const d=await cjFetch("/logistic/freightCalculate",{method:"POST",body:JSON.stringify(payload)});const rows=Array.isArray(d.data)?d.data:[];if(!rows.length)throw new Error("Aucune méthode de livraison CJ disponible pour cette adresse.");const priced=rows.map(x=>({raw:x,total:Number(x.totalPostageFee??x.logisticPrice??0)+Number(x.taxesFee||0)+Number(x.clearanceOperationFee||0)})).filter(x=>x.total>0);if(!priced.length)throw new Error("CJ n’a retourné aucun tarif de livraison exploitable.");priced.sort((a,b)=>a.total-b.total);const best=priced[0],rate=await usdToEur(),buffer=Math.max(0,Number(process.env.CJ_FREIGHT_BUFFER_PCT||0))/100,eur=best.total*rate*(1+buffer);return {amountUsd:Number(best.total.toFixed(2)),amountEur:Number(eur.toFixed(2)),logisticName:best.raw.logisticName,aging:best.raw.logisticAging||"",cjItems,quotedAt:new Date().toISOString()}}
export async function fulfillPaidOrderWithCJ(order){if(order.cj?.orderId||order.cj?.status==="manual_personalization")return order;const cjLines=order.items.filter(i=>PRODUCTS[i.id]?.cj),nonCj=order.items.filter(i=>!PRODUCTS[i.id]?.cj);if(!cjLines.length)return {...order,cj:{...(order.cj||{}),status:nonCj.length?"manual_personalization":"not_applicable"}};const q=order.shippingQuote;if(!q?.logisticName)throw new Error("Tarif/logistique CJ absent de la commande.");const products=[];for(const line of cjLines){const p=PRODUCTS[line.id],v=await resolveVid(p.sku);products.push({vid:v.vid,sku:p.sku,quantity:line.quantity||1,storeLineItemId:String(line.id)})}const c=order.customer;const payload={orderNumber:order.id,shippingZip:c.postalCode,shippingCountry:"France",shippingCountryCode:"FR",shippingProvince:c.city||"France",shippingCity:c.city,shippingPhone:c.phone,shippingCustomerName:`${c.firstName} ${c.lastName}`,shippingAddress:c.address,email:c.email,payType:2,logisticName:q.logisticName,fromCountryCode:"CN",platform:"Api",iossType:3,iossNumber:"CJ-IOSS",orderFlow:1,products};const d=await cjFetch("/shopping/order/createOrderV2",{method:"POST",body:JSON.stringify(payload)}),data=d.data||{};return {...order,cj:{status:data.orderStatus||"submitted",orderId:data.orderId||"",shipmentOrderId:data.shipmentOrderId||"",logisticName:q.logisticName,submittedAt:new Date().toISOString(),actualPaymentUsd:data.actualPayment??null,postageAmountUsd:data.postageAmount??null,iossAmountUsd:data.iossAmount??null,intercepts:data.interceptOrderReasons||[]}}}
export async function syncCJOrder(order){if(!order.cj?.orderId)return order;try{const d=await cjFetch(`/shopping/order/getOrderDetail?orderId=${encodeURIComponent(order.cj.orderId)}`),x=d.data||{},trackingNumber=x.trackNumber||order.trackingNumber||"",carrier=x.trackingProvider||x.logisticName||order.carrier||"",trackingUrl=x.trackingUrl||order.trackingUrl||"";return {...order,cj:{...order.cj,status:x.orderStatus||order.cj.status,lastSyncAt:new Date().toISOString()},trackingNumber,carrier,trackingUrl,fulfillmentStatus:trackingNumber?"shipped":order.fulfillmentStatus||"ordered"}}catch(e){return {...order,cj:{...order.cj,lastSyncError:e.message,lastSyncAt:new Date().toISOString()}}}}
