import {connectLambda,getStore} from "@netlify/blobs";
export const configureBlobs=e=>connectLambda(e);
export const orderStore=()=>getStore("evida-orders");
export const photoStore=()=>getStore("evida-private-photos");
export const checkoutStore=()=>getStore("evida-checkout-index");
export const customerStore=()=>getStore("evida-customers");
export const customerTokenStore=()=>getStore("evida-customer-tokens");
export const contestStore=()=>getStore("evida-contest-entries");
export const contestCheckoutStore=()=>getStore("evida-contest-checkouts");
export const contestEmailStore=()=>getStore("evida-contest-emails");
export const voucherStore=()=>getStore("evida-vouchers");
export const jsonHeaders=(origin="")=>({"Access-Control-Allow-Origin":["https://evida-france.github.io","https://evida-france.netlify.app"].includes(origin)?origin:"https://evida-france.github.io","Access-Control-Allow-Headers":"Content-Type, Authorization","Access-Control-Allow-Methods":"GET, POST, PATCH, OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});
export function cleanText(v,max=200){return String(v??"").trim().replace(/[<>]/g,"").slice(0,max)}
export async function verifySumUpCheckout(id){const k=process.env.SUMUP_API_KEY;if(!k||!id)return null;const r=await fetch(`https://api.sumup.com/v0.1/checkouts/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${k}`}});return r.ok?r.json():null}
export function publicOrder(o){if(!o)return o;const c={...o};delete c.accessToken;delete c.checkoutUrl;return c}
async function sendMail({to,subject,html}){const apiKey=process.env.RESEND_API_KEY,from=process.env.EVIDA_FROM_EMAIL;if(!apiKey||!from)return false;const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({from,to:[to],subject,html})});return r.ok}
export async function sendConfirmation(order){if(order.confirmationSentAt)return order;const ok=await sendMail({to:order.customer.email,subject:`Commande ÉVIDA ${order.id} confirmée`,html:`<h1>Merci pour votre commande</h1><p>Bonjour ${order.customer.firstName},</p><p>Votre paiement est confirmé.</p><p><strong>Commande :</strong> ${order.id}</p><p><strong>Total payé :</strong> ${(order.total/100).toFixed(2).replace(".",",")} €</p><p>Votre commande fournisseur est traitée automatiquement.</p><p>ÉVIDA</p>`});return ok?{...order,emailStatus:"sent",confirmationSentAt:new Date().toISOString()}:{...order,emailStatus:"configuration_required_or_failed"}}
export async function sendShippingConfirmation(order){if(order.shippingEmailSentAt||!order.trackingNumber)return order;const ok=await sendMail({to:order.customer.email,subject:`Votre commande ÉVIDA ${order.id} a été expédiée`,html:`<h1>Votre commande est en route</h1><p>Bonjour ${order.customer.firstName},</p><p>Votre commande <strong>${order.id}</strong> a été expédiée.</p><p><strong>Transporteur :</strong> ${order.carrier||"Transporteur partenaire"}</p><p><strong>Numéro de suivi :</strong> ${order.trackingNumber}</p>${order.trackingUrl?`<p><a href="${order.trackingUrl}">Suivre mon colis</a></p>`:""}<p>ÉVIDA</p>`});return ok?{...order,shippingEmailStatus:"sent",shippingEmailSentAt:new Date().toISOString()}:{...order,shippingEmailStatus:"configuration_required_or_failed"}}
export async function sendContestConfirmation(entry){if(entry.confirmationSentAt)return entry;const ok=await sendMail({to:entry.email,subject:"Participation ÉVIDA confirmée — Jeu concours iPhone 16 Pro Max",html:`<h1>Participation confirmée</h1><p>Bonjour ${entry.firstName},</p><p>Votre paiement de 19,99 € est confirmé.</p><p><strong>Code du bon : ${entry.voucherCode}</strong></p><p>ÉVIDA</p>`});return ok?{...entry,emailStatus:"sent",confirmationSentAt:new Date().toISOString()}:{...entry,emailStatus:"configuration_required_or_failed"}}
